ui_patterns_source.main_page_content:
  type: ignore
  label: 'Source: Main page content'

ui_patterns_source.local_actions:
  type: ignore
  label: 'Source: Local actions'

ui_patterns_source.local_tasks:
  type: ignore
  label: 'Source: Local tasks'
  
ui_patterns_source.page_title:
  type: ignore
  label: 'Source: Page title'
