include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - "/includes/include.drupalci.main.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"

variables:
  # Enable contributors to disable PHPMD tests.
  SKIP_PHPMD: 0
  # Enable contributors to disable e2e tests.
  SKIP_E2E_TESTS: 0

  PLAYWRIGHT_DEBUG_LEVEL: info
  PLAYWRIGHT_TEST_PROJECT: firefox
  PLAYWRIGHT_TEST_TAG: display_builder_min

  # Needed to allow this to run locally.
  # https://project.pages.drupalcode.org/gitlab_templates/info/test-locally/
  DRUPALORG_CI_SERVER_URL: https://git.drupalcode.org
  PHPUNIT_FAIL_ON_PHPUNIT_DEPRECATION: 0

.manual-rule: &manual-rule
  - when: manual
    allow_failure: true

## Define some rules to lighten the CI, inspiration from Canvas:
## https://git.drupalcode.org/project/canvas/-/blob/1.x/.gitlab-ci.yml

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.is-push-rule: &is-push-rule
  if: $CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_ROOT_NAMESPACE == "project"

.php-files-change-rule: &php-files-change-rule
  - if: $_FOR_EVERY_MR_COMMIT == "true" || $_FOR_EVERY_MR_COMMIT == null
    changes:
      - "**/*.{php,module,inc,install,theme,profile}"
    when: on_success

.css-files-change-rule: &css-files-change-rule
  - if: $_FOR_EVERY_MR_COMMIT == "true" || $_FOR_EVERY_MR_COMMIT == null
    changes:
      - "**/*.css"
    when: on_success

.js-files-change-rule: &js-files-change-rule
  - if: $_FOR_EVERY_MR_COMMIT == "true" || $_FOR_EVERY_MR_COMMIT == null
    changes:
      - "**/*.js"
    when: on_success

.module-config-files-change-rule: &module-config-files-change-rule
  - if: $_FOR_EVERY_MR_COMMIT == "true" || $_FOR_EVERY_MR_COMMIT == null
    changes:
      # config schema and/or default config
      - config
      - modules/**/config
    when: on_success

composer-lint:
  allow_failure: false
  rules:
    - !reference [.skip-composer-lint-rule]
    - *is-push-rule
    - *php-files-change-rule
    - changes:
        - composer.json
      when: on_success
    - *manual-rule

phpcs:
  allow_failure: false
  rules:
    - !reference [.skip-phpcs-rule]
    - *is-push-rule
    - *php-files-change-rule
    # Also run whenever we catch up to the upstream PHPCS rules.
    - changes:
        - .phpcs.xml
      when: on_success
    - *manual-rule

phpstan:
  allow_failure: false
  rules:
    - !reference [.skip-phpstan-rule]
    - *is-push-rule
    - *php-files-change-rule
    - *manual-rule

phpunit:
  allow_failure: false
  variables:
    _PHPUNIT_EXTRA: ''
  rules:
    - !reference [.skip-phpunit-rule]
    - *is-push-rule
    - *php-files-change-rule
    - *module-config-files-change-rule
    - *manual-rule

eslint:
  allow_failure: false
  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - !reference [.skip-eslint-rule]
    - *is-push-rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "**/*.js"
        - "**/*.yml"
    - *manual-rule

stylelint:
  allow_failure: false
  rules:
    - !reference [.skip-stylelint-rule]
    - *is-push-rule
    - *css-files-change-rule
    - *manual-rule

cspell:
  allow_failure: false
  variables:
    _CSPELL_IGNORE_PATHS: '**/fixtures/*.yml, *.neon, **/*.story.yml, **/build.env, **/*.patch, **/tests/playwright'

## PHPMD job in Drupal CI ##

.skip-phpmd-rule: &skip-phpmd-rule
  if: '$SKIP_PHPMD == "1"'
  when: never

.phpmd-base:
  stage: validate
  needs:
    - composer
  before_script:
    - curl -fsSL https://phpmd.org/static/latest/phpmd.phar -o vendor/bin/phpmd
    - chmod +x vendor/bin/phpmd
  script:
    - php --version
    - vendor/bin/phpmd --version
    - |
      BASELINE_FILE="${_WEB_ROOT}/modules/custom/${CI_PROJECT_NAME}/.phpmd.baseline.xml"
      PHPMD_CONFIG="${_WEB_ROOT}/modules/custom/${CI_PROJECT_NAME}/.phpmd.xml"
      if [ -f "$BASELINE_FILE" ]; then
        sed -i "s#/builds/project/display_builder#${CI_PROJECT_DIR}#g" "$BASELINE_FILE"
      fi
      if [ -f "$PHPMD_CONFIG" ]; then
        BASELINE_ARG=""
        if [ -f "$BASELINE_FILE" ]; then
          BASELINE_ARG="--baseline-file $BASELINE_FILE"
        fi
        vendor/bin/phpmd "${_WEB_ROOT}/modules/custom/${CI_PROJECT_NAME}" gitlab "$PHPMD_CONFIG" --exclude 'tests/*,**/tests/*' $BASELINE_ARG > phpmd-quality-report.json || true
        vendor/bin/phpmd "${_WEB_ROOT}/modules/custom/${CI_PROJECT_NAME}" text "$PHPMD_CONFIG" --exclude 'tests/*,**/tests/*' $BASELINE_ARG
      else
        echo "[Notice] File .phpmd.xml not found at ${PHPMD_CONFIG}, skipping phpmd."
      fi
  allow_failure: false
  artifacts:
    expose_as: phpmd
    when: always
    expire_in: 6 mos
    reports:
      codequality: phpmd-quality-report.json
    name: artifacts-$CI_PIPELINE_ID-$CI_JOB_NAME_SLUG
    paths:
      - phpmd-quality-report.json

phpmd:
  extends: .phpmd-base
  rules:
    - exists:
      - web/modules/custom/display_builder/.phpmd.baseline.xml
    - *skip-phpmd-rule
    - !reference [.php-files-exist-rule]
    - *is-push-rule
    - *php-files-change-rule
    - *manual-rule

### Playwright tests in ci. ###

# Basic Playwright rules.
.skip-e2e-tests-rule: &skip-e2e-tests-rule
  if: '$SKIP_E2E_TESTS == "1"'
  when: never

.playwright-tests-exist-rule: &playwright-tests-exist-rule
  - exists:
      - tests/src/Playwright/Tests/*.spec.*
      - modules/*/tests/src/Playwright/Tests/*.spec.*
      - tests/modules/*/tests/src/Playwright/Tests/*.spec.*
    when: on_success

.playwright-base:
  # @see https://github.com/devdrupal33/display_builder_test
  image: ghcr.io/devdrupal33/display_builder_test:main
  extends: .test-variables
  stage: test
  services:
    - !reference [.with-database]
  rules:
    - *skip-e2e-tests-rule
    - *playwright-tests-exist-rule
    - *manual-rule
  variables:
    # Standard variables for Playwright. Mostly similar to NightwatchJS tests.
    # This is required for the job to work.
    DRUPAL_TEST_BASE_URL: "${SIMPLETEST_BASE_URL}"
    DRUPAL_TEST_SETUP_FILE: '${CI_PROJECT_DIR}/tests/src/TestSite/DisplayBuilderTestSetup.php'
    DRUPAL_WEB_ROOT: $_WEB_ROOT
    DRUPAL_TEST_WEBSERVER_USER: www-data
    # Specific Playwright job rules.
    PLAYWRIGHT_SKIP_TEARDOWN: true
    # From the Docker image
    PLAYWRIGHT_BROWSERS_PATH: /var/www/pw-browsers
  before_script:
    - !reference [.check-composer-end-code]
    - !reference [.setup-webserver]
    - !reference [.simpletest-db]
    # Important to set here to have a value from simpletest-db.
    - export DRUPAL_TEST_DB_URL=$SIMPLETEST_DB
    - !reference [.show-environment-variables]
    - !reference [.show-context]
    # Install local shoelace and htmx sse libraries for tests.
    - echo -e "\e[0Ksection_start:`date +%s`:lib_install[collapsed=true]\r\e[0KNPM lib install..."
    - if [ ! -f ${CI_PROJECT_DIR}/${DRUPAL_WEB_ROOT}/libraries/shoelace/node_modules/@shoelace-style/shoelace/cdn/shoelace.js ]; then
        mkdir -p ${CI_PROJECT_DIR}/${DRUPAL_WEB_ROOT}/libraries/shoelace;
        cd ${CI_PROJECT_DIR}/${DRUPAL_WEB_ROOT}/libraries/shoelace && npm init -y && npm install @shoelace-style/shoelace;
        cd ${CI_PROJECT_DIR};
      fi
    - if [ ! -f ${CI_PROJECT_DIR}/${DRUPAL_WEB_ROOT}/libraries/htmx-ext-sse/node_modules/htmx-ext-sse/dist/sse.min.js ]; then
        mkdir -p ${CI_PROJECT_DIR}/${DRUPAL_WEB_ROOT}/libraries/htmx-ext-sse;
        cd ${CI_PROJECT_DIR}/${DRUPAL_WEB_ROOT}/libraries/htmx-ext-sse && npm init -y && npm install htmx-ext-sse;
        cd ${CI_PROJECT_DIR};
      fi
    - echo -e "\e[0Ksection_end:`date +%s`:lib_install\r\e[0K"
    # Install playwright and packages, already cached in the image.
    - echo -e "\e[0Ksection_start:`date +%s`:playwright_install[collapsed=true]\r\e[0KPlaywright install..."
    - npm install
    - npx playwright install
    - echo -e "\e[0Ksection_end:`date +%s`:playwright_install\r\e[0K"
  script:
    - npx playwright install --list
    - npx playwright test --project=${PLAYWRIGHT_TEST_PROJECT} --grep @${PLAYWRIGHT_TEST_TAG}
  after_script:
    - mkdir -p $CI_PROJECT_DIR/logs
    - cp -R /var/log/apache2 $CI_PROJECT_DIR/logs/apache2
    - cp -R /var/log/supervisor $CI_PROJECT_DIR/logs/supervisor
    - |
      cat > ${CI_PROJECT_DIR}/test-results/links.json << EOF
      {
        "playwright": [
          {
            "external_link": {
              "label": "Playwright test report",
              "url": "https://${CI_PROJECT_NAMESPACE}.${CI_PAGES_DOMAIN}/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/playwright-report/index.html"
            }
          }
        ]
      }
      EOF
  artifacts:
    expose_as: 'Playwright Test Reports'
    when: always
    expire_in: 6 mos
    paths:
      - playwright-report/
      - test-results/
      - logs/
    reports:
      junit:
        - test-results/playwright.xml
      annotations: test-results/links.json

playwright (all):
  extends: .playwright-base
  allow_failure: true
  rules:
    - *manual-rule
  variables:
    PLAYWRIGHT_TEST_PROJECT: firefox
    PLAYWRIGHT_TEST_TAG: display_builder

playwright (min):
  extends: .playwright-base
  allow_failure: false
  variables:
    PLAYWRIGHT_TEST_PROJECT: "*"
    PLAYWRIGHT_TEST_TAG: display_builder_min
