<?php

/**
 * @file
 * Install hooks for display_builder.
 */

declare(strict_types=1);

/**
 * Implements hook_uninstall().
 */
function display_builder_uninstall(): void {
  $storage = \Drupal::service('entity_type.manager')->getStorage('display_builder_instance');
  $instances = $storage->loadMultiple();
  $storage->delete($instances);

  \Drupal::service('plugin.cache_clearer')->clearCachedDefinitions();
}
