display_builder.profile.*:
  type: config_entity
  label: Display builder profile
  mapping:
    id:
      type: machine_name
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: uuid
    description:
      type: text
    debug:
      type: boolean
      label: 'Debug mode'
    islands:
      type: sequence
      label: 'Islands'
      sequence:
        type: display_builder.islands.[%key]
    weight:
      type: weight
      label: Weight

display_builder.islands.*:
  type: mapping
  label: 'Island configuration'
  mapping:
    status:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight
    region:
      type: machine_name
      label: Region

display_builder.islands.state:
  type: mapping
  mapping:
    status:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight
    publish:
      type: display_builder.toolbar.button
    restore:
      type: display_builder.toolbar.button
    revert:
      type: display_builder.toolbar.button

display_builder.islands.history:
  type: mapping
  mapping:
    status:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight
    undo:
      type: display_builder.toolbar.button
    redo:
      type: display_builder.toolbar.button
    clear:
      type: display_builder.toolbar.button

display_builder.islands.controls:
  type: mapping
  mapping:
    status:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight
    highlight:
      type: display_builder.toolbar.button
    fullscreen:
      type: display_builder.toolbar.button
    theme:
      type: display_builder.toolbar.button
    help:
      type: display_builder.toolbar.button

display_builder.islands.component_library:
  type: mapping
  mapping:
    exclude:
      type: sequence
      sequence:
        type: string
    exclude_id:
      type: string
    component_status:
      type: sequence
      sequence:
        type: string
    include_no_ui:
      type: boolean
    show_grouped:
      type: boolean
    show_variants:
      type: boolean
    show_mosaic:
      type: boolean
    status:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight

display_builder.islands.block_library:
  type: mapping
  mapping:
    exclude:
      type: sequence
      sequence:
        type: string
    exclude_id:
      type: sequence
      sequence:
        type: string
    status:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight

display_builder.islands.collaboration:
  type: mapping
  mapping:
    image_field:
      type: machine_name
    image_style:
      type: machine_name
    status:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight

display_builder.islands.viewport:
  type: mapping
  mapping:
    exclude:
      type: sequence
      sequence:
        type: string
    format:
      type: string
      label: Format
    status:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight

display_builder.islands.back:
  type: mapping
  mapping:
    status:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight
    back:
      type: display_builder.toolbar.button

display_builder.pattern_preset.*:
  type: config_entity
  label: Display builder Preset
  mapping:
    uuid:
      type: uuid
    id:
      type: machine_name
      label: ID
    weight:
      type: weight
      label: Weight
    label:
      type: label
      label: Label
    description:
      type: text
      label: Description
    group:
      type: string
      label: Group
    sources:
      label: 'UI Patterns sources'
      type: sequence
      sequence:
        type: ignore

ui_patterns_slot_source.third_party_setting.ui_styles:
  label: 'UI Styles settings'
  type: mapping
  mapping:
    styles:
      type: ui_styles.selected_mapping

display_builder.toolbar.button:
  label: 'Label and icon visibility'
  type: mapping
  mapping:
    value:
      type: string
      constraints:
        Choice:
          - label
          - icon
          - icon_label
          - hidden
      FullyValidatable: ~
