display_builder.display_builder.*:
  type: config_entity
  label: Display builder
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
    library:
      type: string
      label: 'Library type'
    debug:
      type: boolean
      label: 'Debug mode'
    island_settings:
      type: mapping
      label: 'Island settings'
      mapping:
        library:
          type: sequence
          label: 'Library island'
          sequence:
            type: display_builder.island_settings.[%key]
        view:
          type: sequence
          label: 'Library island'
          sequence:
            type: display_builder.island_settings.[%key]
        button:
          type: sequence
          label: 'Library island'
          sequence:
            type: display_builder.island_settings.[%key]
        contextual:
          type: sequence
          label: 'Library island'
          sequence:
            type: display_builder.island_settings.[%key]
        menu:
          type: sequence
          label: 'Library island'
          sequence:
            type: display_builder.island_settings.[%key]
    island_configuration:
      label: 'Island configuration'
      # @todo set this configuration, ignore for now.
      type: ignore
    weight:
      type: weight
      label: Weight

display_builder.island_settings.*:
  type: mapping
  label: 'Island settings'
  mapping:
    enable:
      type: boolean
      label: Enabled
    weight:
      type: string
      label: Weight
    options:
      type: string
      label: Options

display_builder.pattern_preset.*:
  type: config_entity
  label: Display builder Preset
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
    theme:
      type: string
    group:
      type: string
    sources:
      label: "UI Patterns sources"
      type: mapping
      mapping:
        source_id:
          type: string
          label: 'Prop source ID'
        source:
          type: ui_patterns_source.[%parent.source_id]
          label: 'Prop source configuration'
        _third_party_settings:
          type: mapping
