display_builder.display_builder.*:
  type: config_entity
  label: Display builder
  mapping:
    id:
      type: machine_name
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: uuid
    description:
      type: text
    library:
      type: string
      label: "Library type"
    debug:
      type: boolean
      label: "Debug mode"
    islands:
      type: sequence
      label: "Islands"
      sequence:
        type: display_builder.islands.[%key]
    weight:
      type: weight
      label: Weight

display_builder.islands.*:
  type: mapping
  label: "Island configuration"
  mapping:
    enable:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight
    region:
      type: machine_name
      label: Region

display_builder.islands.history:
  type: mapping
  mapping:
    display_clear_button:
      type: boolean
    enable:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight

display_builder.islands.component_library:
  type: mapping
  mapping:
    providers:
      type: sequence
      sequence:
        type: string
    status:
      type: sequence
      sequence:
        type: string
    include_no_ui:
      type: boolean
    show_grouped:
      type: boolean
    show_variants:
      type: boolean
    show_mosaic:
      type: boolean
    enable:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight

display_builder.islands.block_library:
  type: mapping
  mapping:
    providers:
      type: sequence
      sequence:
        type: string
    enable:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight

display_builder.islands.active_users:
  type: mapping
  mapping:
    image_field:
      type: machine_name
    image_style:
      type: machine_name
    enable:
      type: boolean
      label: Enabled
    weight:
      type: weight
      label: Weight

display_builder.pattern_preset.*:
  type: config_entity
  label: Display builder Preset
  mapping:
    id:
      type: machine_name
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: uuid
    description:
      type: text
    group:
      type: string
    sources:
      label: "UI Patterns sources"
      type: mapping
      mapping:
        source_id:
          type: machine_name
          label: 'Prop source ID'
        source:
          type: ui_patterns_source.[%parent.source_id]
          label: 'Prop source configuration'
        _third_party_settings:
          type: mapping
