<?php

declare(strict_types=1);

namespace Drupal\Tests\display_builder\Kernel;

use Drupal\display_builder\Entity\Instance;
use Drupal\display_builder\Plugin\display_builder\Island\BuilderPanel;
use Drupal\display_builder\Plugin\display_builder\Island\ViewPanelBase;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\RunTestsInSeparateProcesses;

/**
 * Test some mechanisms $renderable = of the BuilderPanel plugin.
 *
 * @internal
 */
#[CoversClass(ViewPanelBase::class)]
#[CoversClass(BuilderPanel::class)]
#[Group('display_builder')]
#[RunTestsInSeparateProcesses]
final class BuilderPanelTest extends DisplayBuilderKernelTestBase {

  /**
   * {@inheritdoc}
   */
  protected static $modules = [
    'system',
    'user',
    'ui_patterns',
    'ui_patterns_field',
    'display_builder',
    'display_builder_test',
  ];

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    parent::setUp();
    $this->installConfig(['system', 'display_builder', 'ui_patterns', 'display_builder_test']);
    $this->installEntitySchema('user');
    $this->installEntitySchema('display_builder_profile');
  }

  /**
   * Test the ::buildSingleBlock() method.
   */
  public function testBuildSingleBlock(): void {
    $instance = Instance::create([
      'id' => 'test_instance',
      'label' => 'Test Instance',
    ]);

    $data = [
      [
        'source_id' => 'block',
        'node_id' => \bin2hex(\random_bytes(8)),
        'source' => [
          'plugin_id' => 'display_builder_test_correct',
        ],
      ],
      [
        'source_id' => 'block',
        'node_id' => \bin2hex(\random_bytes(8)),
        'source' => [
          'plugin_id' => 'display_builder_test_empty',
        ],
      ],
      [
        'source_id' => 'block',
        'node_id' => \bin2hex(\random_bytes(8)),
        'source' => [
          'plugin_id' => 'display_builder_test_multi_root',
        ],
      ],
      [
        'source_id' => 'block',
        'node_id' => \bin2hex(\random_bytes(8)),
        'source' => [
          'plugin_id' => 'display_builder_test_no_attributes',
        ],
      ],
      [
        'source_id' => 'block',
        'node_id' => \bin2hex(\random_bytes(8)),
        'source' => [
          'plugin_id' => 'system_messages_block',
        ],
      ],
      [
        'source_id' => 'entity_field',
        'node_id' => \bin2hex(\random_bytes(8)),
      ],
    ];
    $builder_panel = $this->createIslandPlugin('builder');
    $renderable = $builder_panel->build($instance, $data, [])['#slots']['content'];
    $this->assertNonAltered($renderable[0]);
    $this->assertWrapper($renderable[2]);
    $this->assertWrapper($renderable[3]);

    // A block that rendered nothing: nothing is coming to fill it, so the
    // placeholder says so rather than blaming the page.
    self::assertStringContainsString('Configure it to make it visible', $this->helpOf($renderable[1]));

    // A page chrome block, which the source replaced before the panel ever
    // saw it. Same shape, opposite promise.
    $this->assertRegionPlaceholder($renderable[4], 'Messages');
    self::assertStringContainsString('replaced by the page value', $this->helpOf($renderable[4]));

    // Not a block, and empty: same placeholder as any other empty node, so
    // the Canvas has one shape for "nothing here" instead of two.
    self::assertStringContainsString('Configure it to make it visible', $this->helpOf($renderable[5]));
    self::assertStringStartsWith('Field: ', (string) $renderable[5]['#slots']['content']['title']['#value']);
  }

  /**
   * A forced block is replaced even though its render is not empty.
   *
   * Local_tasks_block emits a wrapper with nothing in it, so the emptiness
   * check never fires. Without the forced list the node renders as an
   * invisible box carrying no node id, which cannot be selected, moved or
   * deleted.
   */
  public function testForcedBlockStaysSelectable(): void {
    $instance = Instance::create([
      'id' => 'test_instance_forced',
      'label' => 'Test Instance',
    ]);

    $data = [
      [
        'source_id' => 'block',
        'node_id' => \bin2hex(\random_bytes(8)),
        'source' => [
          'plugin_id' => 'local_tasks_block',
        ],
      ],
    ];

    $renderable = $this->createIslandPlugin('builder')->build($instance, $data, [])['#slots']['content'];

    $this->assertRegionPlaceholder($renderable[0], 'Tabs');
    self::assertSame($data[0]['node_id'], $renderable[0]['#attributes']['data-node-id'] ?? NULL);
  }

  /**
   * Assert the block renderable was not altered.
   *
   * @param array $renderable
   *   The block renderable, as generated by the BuilderPanel island.
   */
  private function assertNonAltered(array $renderable): void {
    $block = $this->container->get('plugin.manager.block')->createInstance('display_builder_test_correct');
    $expectations = $block->build();
    // We don't check #attributes, #attached or #cache because they got the
    // HTMX additions (core's Htmx::applyTo() attaches the core/drupal.htmx
    // library and cacheable metadata to every element it is applied to).
    unset($renderable['#attributes'], $expectations['#attributes'], $renderable['#attached'], $expectations['#attached'], $renderable['#cache'], $expectations['#cache']);

    self::assertSame($expectations, $renderable);
  }

  /**
   * Assert the block renderable was replaced by a placeholder.
   *
   * @param array $renderable
   *   The block renderable, as generated by the BuilderPanel island.
   */
  private function assertPlaceholder(array $renderable): void {
    self::assertSame('component', $renderable['#type']);
    self::assertSame('display_builder:placeholder', $renderable['#component']);
  }

  /**
   * Assert the block renderable was replaced by a named region placeholder.
   *
   * @param array $renderable
   *   The block renderable, as generated by the BuilderPanel island.
   * @param string $label
   *   The region name expected in the title slot.
   */
  private function assertRegionPlaceholder(array $renderable, string $label): void {
    $this->assertPlaceholder($renderable);
    self::assertSame('region', $renderable['#props']['variant']);
    self::assertSame($label, (string) $renderable['#slots']['content']['title']['#value']);
  }

  /**
   * The sentence rendered under a region placeholder's name.
   *
   * @param array $renderable
   *   The block renderable, as generated by the BuilderPanel island.
   *
   * @return string
   *   The help sentence.
   */
  private function helpOf(array $renderable): string {
    return (string) $renderable['#slots']['content']['help']['#value'];
  }

  /**
   * Assert the block renderable was put in a wrapper.
   *
   * @param array $renderable
   *   The block renderable, as generated by the BuilderPanel island.
   */
  private function assertWrapper(array $renderable): void {
    self::assertSame('html_tag', $renderable['#type']);
    self::assertArrayHasKey('content', $renderable);
  }

}
