views.display_extender.display_builder:
  type: views_display_extender
  mapping:
    display_builder:
      type: string
      label: 'Display builder config'
    instance:
      type: string
      label: 'Display builder instance'
