views.display_extender.display_builder:
  type: views_display_extender
  mapping:
    display_builder:
      type: string
      label: "Display builder config"
    sources:
      # @todo set this configuration, ignore for now.
      type: ignore
      label: "Display Builder sources."
