core.entity_view_display.*.*.*.third_party.display_builder:
  type: mapping
  label: 'Display Builder settings'
  mapping:
    display_builder:
      label: "Display Builder profile"
      constraints:
        ConfigExists:
          prefix: 'display_builder.display_builder.'
    sources:
      label: "UI Patterns sources"
      type: sequence
      sequence:
        type: ui_patterns_source.[id]
