core.entity_view_display.*.*.*.third_party.display_builder:
  label: 'Display Builder settings'
  type: mapping
  mapping:
    display_builder:
      label: "Display Builder profile"
      type: string
      constraints:
        ConfigExists:
          prefix: 'display_builder.display_builder.'
    sources:
      label: "UI Patterns sources"
      type: sequence
      sequence:
        type: ui_patterns_source.[source_id]
  constraints:
    FullyValidatable: ~
