<?php

/**
 * @file
 * Contains install file.
 */

declare(strict_types=1);

/**
 * Implements hook_install().
 */
function display_builder_views_install(): void {
  $config = \Drupal::service('config.factory')->getEditable('views.settings');
  /** @var array $display_extenders */
  $display_extenders = $config->get('display_extenders') ?: [];
  $display_extenders[] = 'display_builder';
  $config->set('display_extenders', $display_extenders);
  $config->save();
}

/**
 * Implements hook_uninstall().
 */
function display_builder_views_uninstall(): void {
  $config = \Drupal::service('config.factory')->getEditable('views.settings');
  /** @var array $display_extenders */
  $display_extenders = $config->get('display_extenders') ?: [];
  $key = \array_search('display_builder', $display_extenders, TRUE);

  if ($key !== FALSE) {
    unset($display_extenders[$key]);
    $config->set('display_extenders', $display_extenders);
    $config->save();
  }
}
