<?php

/**
 * @file
 * Contains install and update functions for Display Builder Page Layout.
 */

declare(strict_types=1);

/**
 * Implements hook_install().
 */
function display_builder_page_layout_install(): void {
  /** @var \Drupal\display_builder_page_layout\DisplayBuilderPageLayoutInterface $configManager */
  $configManager = Drupal::service('display_builder_page_layout.config_manager');
  $configManager->newPageLayout();
}

/**
 * Implements hook_uninstall().
 */
function display_builder_page_layout_uninstall(): void {
  /** @var \Drupal\display_builder_page_layout\DisplayBuilderPageLayoutInterface $configManager */
  $configManager = Drupal::service('display_builder_page_layout.config_manager');
  $configManager->delete();
}
