<?php

/**
 * @file
 * Contains the display builder page layout module.
 */

declare(strict_types=1);

/**
 * Implements hook_theme_registry_alter().
 */
function display_builder_page_layout_theme_registry_alter(array &$theme_registry): void {
  $isAdmin = Drupal::service('router.admin_context')->isAdminRoute();

  if ($isAdmin) {
    return;
  }
  $template_uri = Drupal::service('extension.list.module')->getPath('display_builder_page_layout') . '/templates';
  $theme_registry['html']['path'] = $template_uri;
  $theme_registry['page']['path'] = $template_uri;
  $theme_registry['region']['path'] = $template_uri;
  // $theme_registry['off_canvas_page_wrapper']['path'] = $template_uri;
}
