display_builder_page_layout.page_layout.*:
  type: config_entity
  label: Page layout
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    display_builder:
      type: string
      label: "Used Display Builder"
    weight:
      type: weight
      label: Weight
    conditions:
      type: sequence
      label: 'Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Condition'
    sources:
      # @todo set this configuration, ignore for now.
      type: ignore
      label: "Display Builder sources."
  constraints:
    FullyValidatable: ~
