display_builder_page_layout.page_layout.*:
  type: config_entity
  label: Page layout
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    weight:
      type: weight
      label: Weight
    conditions:
      type: sequence
      label: 'Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Condition'
    profile:
      label: 'Display Builder profile'
      type: string
      constraints:
        ConfigExists:
          prefix: 'display_builder.profile.'
    sources:
      label: 'UI Patterns sources'
      type: sequence
      sequence:
        type: ui_patterns_source.[source_id]
  constraints:
    FullyValidatable: ~

ui_patterns_source.main_page_content:
  type: ignore
  label: 'Source: Main page content'

ui_patterns_source.local_actions:
  type: ignore
  label: 'Source: Local actions'

ui_patterns_source.local_tasks:
  type: ignore
  label: 'Source: Local tasks'

ui_patterns_source.page_title:
  type: ignore
  label: 'Source: Page title'
