<?php

/**
 * @file
 * Contains the display builder entity view module.
 */

declare(strict_types=1);

/**
 * Implements hook_module_implements_alter().
 */
function display_builder_entity_view_module_implements_alter(array &$implementations, int|string $hook): void {
  if ($hook === 'entity_view_alter') {
    // Ensure that this module's implementation of hook_entity_view_alter() runs
    // last so that other modules that use this hook to render extra fields will
    // run before it.
    $group = $implementations['display_builder_entity_view'];
    unset($implementations['display_builder_entity_view']);
    $implementations['display_builder_entity_view'] = $group;
  }
}
