<?php

/**
 * @file
 * Contains the display builder entity view module.
 */

declare(strict_types=1);

/**
 * Implements hook_preprocess_entity().
 *
 * Special callback function for entity.html.twig.
 *
 * Reproduce Core preprocesses for node, media, taxonomy_term to populate the
 * content variable.
 */
function display_builder_entity_view_preprocess_entity(array &$variables): void {
  $variables += ['content' => []];

  if (isset($variables['elements']['content'])) {
    $variables['content']['content'] = $variables['elements']['content'];
  }
}
